2018-03-15 20:58:35.090031: I tensorflow/core/common_runtime/gpu/gpu_device.cc:938] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB
major: 6 minor: 0 memoryClockRate (GHz) 1.3285
pciBusID 0000:86:00.0
Total memory: 15.89GiB
Free memory: 15.60GiB
2018-03-15 20:58:35.090094: I tensorflow/core/common_runtime/gpu/gpu_device.cc:959] DMA: 0 
2018-03-15 20:58:35.090105: I tensorflow/core/common_runtime/gpu/gpu_device.cc:969] 0:   Y 
2018-03-15 20:58:35.090141: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1028] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:86:00.0)
Traceback (most recent call last):
  File "main.py", line 356, in <module>
    tf.app.run(main=main)
  File "/mnt/storage/easybuild/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 304, in main
    data, labels = get_batch_of_batchs(mnist)
TypeError: get_batch_of_batchs() takes exactly 2 arguments (1 given)
srun: error: gpu07: task 0: Exited with exit code 1
